--- #syncing remote folder with local
- hosts: all
  connection: ssh
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Dowload file from remote system
      fetch:
        src: /etc/passwd
        dest: /tmp/paswd_"{{inventory_hostname}}"
  

